config:
    session: ./common/sessions.json
    commodity: ./common/stk_comms.json
    contract: ./common/stocks.json
    profile: shengliTest
    parser: ParserShengLi.dll

shengliTest:
    servers:
    -   host: '10.141.63.13'
        port: '10001'
        user: 'test'
        pass: 'test'
        enable_sse: '1'
        enable_sze: '1'
    
    REPORT:
    -   report_when_quit: '0'
        tick_detach_enable:'0'
    
    NIC_TYPE:
        nic_type:'1'
     
    EFH_SZE_LEV2_TICK:
        enable:'1'
        cpu_id : '5'
        multicast_ip :'233.57.1.101'
        multicast_port :'37101'
        data_ip :'4.4.4.63'
        data_port :'0'
        eth_name :'eth7'
        cache_size :'256'
        force_normal_socket :'0'
        proc_data_wait_time :'10'
        normal_socket_rxbuf :'10'
        out_of_order_correction :'0'
        
    EFH_SZE_LEV2_IDX:
        enable:'1'
        cpu_id : '2'
        multicast_ip :'233.57.1.102'
        multicast_port :'37102'
        data_ip :'4.4.4.63'
        data_port :'0'
        eth_name :'eth7'
        cache_size :'256'
        force_normal_socket :'0'
        proc_data_wait_time :'10'
        normal_socket_rxbuf :'10'
        out_of_order_correction :'0'
        
    EFH_SZE_LEV2_SNAP:
        enable:'1'
        cpu_id : '1'
        multicast_ip :'233.57.1.100'
        multicast_port :'37100'
        data_ip :'4.4.4.63'
        data_port :'0'
        eth_name :'eth7'
        cache_size :'256'
        force_normal_socket :'0'
        proc_data_wait_time :'10'
        normal_socket_rxbuf :'10'
        out_of_order_correction :'0'

    EFH_SZE_LEV2_AFTER_CLOSE:
        enable:'1'
        cpu_id : '3'
        multicast_ip :'233.57.1.103'
        multicast_port :'37103'
        data_ip :'4.4.4.63'
        data_port :'0'
        eth_name :'eth7'
        cache_size :'256'
        force_normal_socket :'0'
        proc_data_wait_time :'10'
        normal_socket_rxbuf :'10'
        out_of_order_correction :'0'    

    EFH_SZE_LEV2_TREE:
        enable:'1'
        cpu_id : '4'
        multicast_ip :'233.57.1.104'
        multicast_port :'37104'
        data_ip :'4.4.4.63'
        data_port :'0'
        eth_name :'eth7'
        cache_size :'256'
        force_normal_socket :'0'
        proc_data_wait_time :'10'
        normal_socket_rxbuf :'10'
        out_of_order_correction :'0'      

    EFH_SZE_LEV2_IBR_TREE:
        enable:'1'
        cpu_id : '4'
        multicast_ip :'233.57.1.105'
        multicast_port :'37105'
        data_ip :'4.4.4.63'
        data_port :'0'
        eth_name :'eth7'
        cache_size :'256'
        force_normal_socket :'0'
        proc_data_wait_time :'10'
        normal_socket_rxbuf :'10'
        out_of_order_correction :'0'         

    EFH_SZE_LEV2_TURNOVER:
        enable:'1'
        cpu_id : '4'
        multicast_ip :'233.57.1.106'
        multicast_port :'37106'
        data_ip :'4.4.4.63'
        data_port :'0'
        eth_name :'eth7'
        cache_size :'256'
        force_normal_socket :'0'
        proc_data_wait_time :'10'
        normal_socket_rxbuf :'10'
        out_of_order_correction :'0'  

    EFH_SZE_LEV2_BOND_SNAP:
        enable:'1'
        cpu_id : '4'
        multicast_ip :'233.57.1.106'
        multicast_port :'37107'
        data_ip :'4.4.4.63'
        data_port :'0'
        eth_name :'eth7'
        cache_size :'256'
        force_normal_socket :'0'
        proc_data_wait_time :'10'
        normal_socket_rxbuf :'10'
        out_of_order_correction :'0'     

    EFH_SZE_LEV2_BOND_TICK:
        enable:'1'
        cpu_id : '4'
        multicast_ip :'233.57.1.106'
        multicast_port :'37108'
        data_ip :'4.4.4.63'
        data_port :'0'
        eth_name :'eth7'
        cache_size :'256'
        force_normal_socket :'0'
        proc_data_wait_time :'10'
        normal_socket_rxbuf :'10'
        out_of_order_correction :'0'    

    EFH_SSE_LEV2_IDX:
        enable:'1'
        cpu_id : '7'
        multicast_ip :'233.57.1.102'
        multicast_port :'37102'
        data_ip :'4.4.4.63'
        data_port :'0'
        eth_name :'eth7'
        cache_size :'256'
        force_normal_socket :'0'
        proc_data_wait_time :'10'
        normal_socket_rxbuf :'10'
        out_of_order_correction :'0'         
        
    EFH_SSE_LEV2_TICK:
        enable:'1'
        cpu_id : '8'
        multicast_ip :'233.57.1.103'
        multicast_port :'37103'
        data_ip :'4.4.4.63'
        data_port :'0'
        eth_name :'eth7'
        cache_size :'256'
        force_normal_socket :'0'
        proc_data_wait_time :'10'
        normal_socket_rxbuf :'10'
        out_of_order_correction :'0' 
        
    EFH_SSE_LEV2_OPTION:
        enable:'1'
        cpu_id : '9'
        multicast_ip :'233.57.1.104'
        multicast_port :'37104'
        data_ip :'4.4.4.63'
        data_port :'0'
        eth_name :'eth7'
        cache_size :'256'
        force_normal_socket :'0'
        proc_data_wait_time :'10'
        normal_socket_rxbuf :'10'
        out_of_order_correction :'0'      

    EFH_SSE_LEV2_SNAP:
        enable:'1'
        cpu_id : '10'
        multicast_ip :'233.57.1.105'
        multicast_port :'37105'
        data_ip :'4.4.4.63'
        data_port :'0'
        eth_name :'eth7'
        cache_size :'256'
        force_normal_socket :'0'
        proc_data_wait_time :'10'
        normal_socket_rxbuf :'10'
        out_of_order_correction :'0'       

    EFH_SSE_LEV2_TREE:
        enable:'1'
        cpu_id : '12'
        multicast_ip :'233.57.1.107'
        multicast_port :'37107'
        data_ip :'4.4.4.63'
        data_port :'0'
        eth_name :'eth7'
        cache_size :'256'
        force_normal_socket :'0'
        proc_data_wait_time :'10'
        normal_socket_rxbuf :'10'
        out_of_order_correction :'0'    

    EFH_SSE_LEV2_BOND_SNAP:
        enable:'1'
        cpu_id : '14'
        multicast_ip :'228.5.6.70'
        multicast_port :'37270'
        data_ip :'4.4.4.63'
        data_port :'0'
        eth_name :'eth7'
        cache_size :'256'
        force_normal_socket :'0'
        proc_data_wait_time :'10'
        normal_socket_rxbuf :'10'
        out_of_order_correction :'0'        

    EFH_SSE_LEV2_BOND_TICK:
        enable:'1'
        cpu_id : '16'
        multicast_ip :'228.5.6.71'
        multicast_port :'37271'
        data_ip :'4.4.4.63'
        data_port :'0'
        eth_name :'eth7'
        cache_size :'256'
        force_normal_socket :'0'
        proc_data_wait_time :'10'
        normal_socket_rxbuf :'10'
        out_of_order_correction :'0'       

    EFH_SSE_LEV2_TICK_MERGE:
        enable:'1'
        cpu_id : '1'
        multicast_ip :'228.5.6.72'
        multicast_port :'37272'
        data_ip :'4.4.4.63'
        data_port :'37272'
        eth_name :'eth7'
        cache_size :'256'
        force_normal_socket :'0'
        proc_data_wait_time :'10'
        normal_socket_rxbuf :'10'
        out_of_order_correction :'0'        
        
    EFH_SSE_LEV2_ETF:
        enable:'1'
        cpu_id : '1'
        multicast_ip :'228.5.6.73'
        multicast_port :'37273'
        data_ip :'4.4.4.63'
        data_port :'37273'
        eth_name :'eth7'
        cache_size :'256'
        force_normal_socket :'0'
        proc_data_wait_time :'10'
        normal_socket_rxbuf :'10'
        out_of_order_correction :'0'      

    EFH_SSE_STATIC_INFO:
        enable:'1'
        cpu_id : '1'
        multicast_ip :'224.0.5.5'
        multicast_port :'8844'
        data_ip :'192.168.18.177'
        data_port :'8844'
        eth_name :'eth7'
        cache_size :'256'
        force_normal_socket :'0'
        proc_data_wait_time :'10'
        normal_socket_rxbuf :'10'
        out_of_order_correction :'0'          