config:
    session: ./common/sessions.json
    commodity: ./common/stk_comms.json
    contract: ./common/stocks.json
    profile: tdfTest
    parser: ParserTDF.dll

tdfTest:
    ip: '58.210.86.54'
    port: '10001'
    user: 'test'
    pass: 'test'
    heartbeat_gap: '10'
    miss_count: '3'
    timeout: '30'
    n_time: '0'
    distribution: '0'
    enable_proxy: false
